apiVersion: v1
kind: Service
metadata:
  name: {{ include "django-project.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "django-project.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "django-project.selectorLabels" . | nindent 4 }}
